### ISSUE TITLE
[BUG] Strange schema of attributes property in RelationshipRequest

### ISSUE THREAD

**Issue by kulla** [nmshd/feedback#11]
**Describe the bug**
We use a webhook to handle relationship requests in an onboarding process. The `attributes` property of such a `RelationshipRequest` has the form

```json
{
  "Lernstand-Mathe": {
    "name": "Lernstand-Mathe",
    "value": "Bruchaddition"
  },
  "Person.familyName": {
    "name": "Person.familyName",
    "value": "Musterfrau"
  },
  "Person.givenName": {
    "name": "Person.givenName",
    "value": "Anna"
  }
}
```

This is a strange form since I either would expect `{ [key: string]: string }` or `{ name: string, value: string }[]` and not a mix of both forms. Thus I think this is a bug.

**To Reproduce**
Steps to reproduce the behavior (see also our code at [enmeshed-middleware.ts](https://github.com/serlo/api.serlo.org/blob/main/packages/server/src/internals/server/enmeshed-middleware.ts)):

1. Setup a connector with a webhook.
2. Setup a relationship with an user and accept it.
3. Listen to the webhook endpoint and log the received payload.

I got the payload:

```js
{
  "relationships": [
    {
      "id": "RELLYXitKJMEMAcNwVhF",
      "template": {
       ...
      },
      "status": "Pending",
      "peer": "id1PZ7tXqGmStSEL6KdBtXMLLETu8RJh1KqU",
      "changes": [
        {
          "id": "RCH1LWM7HGpo0aSa0nG0",
          "request": {
            ...
            "content": {
              "attributes": {
                "Lernstand-Mathe": {
                  "name": "Lernstand-Mathe",
                  "value": "Bruchaddition"
                },
                "Person.familyName": {
                  "name": "Person.familyName",
                  "value": "Musterfrau"
                },
                "Person.givenName": {
                  "name": "Person.givenName",
                  "value": "Anna"
                }
              },
              ...
            }
          },
          "status": "Pending",
          "type": "Creation"
        }
      ]
    }
  ],
  "messages": []
}
```

**Expected behavior**
Either attributes has the form `{ [key: string]: string }` or `{ name: string, value: string }[]`.

**Environment**
 - Product: Connector
 - Version: 2.2.1

**Comment by jkoenig134** [comment]
Actually this is is a problem with the App, we will investigate.

**Comment by stnmtz** [comment]
First thanks for your feedback and the report! 

The app receives names of required or optional attributes within the template. Those are matched against the user's data. Currently, these attribute names - and actually the return values - are unique, meaning that if in the template "Person.givenName" is queried, only one "Person.givenName" can be returned. The app then summarizes the required and optional attributes into one map, with the keys being the queried attribute names and the values being the actual attribute within the user's data. That's for the templator to match its queried attribute names against the received attributes. That is why the response is a map rather than required and optional arrays.

In my point of view, this so far makes sense and thus it is not a bug ;) I do see the "strangeness" however: We do know that the current attribute handling and querying has major limitations. That's why we began to define requests which actually should be used also within templates in the future. Thus, a template would define several requests (e.g. for attributes, for privacy, ...) and the app would respond to these requests within the relationship requests. 

We are currently working on the details. However, I would see also a map for the responses there (with the request id/key as the index). Would you rather have an array there?

**Comment by kulla** [comment]
> The app then summarizes the required and optional attributes into one map, with the keys being the queried attribute names and the values being the actual attribute within the user's data.

That's understandable. Lets take the example of `Person.givenName`. Isn't the user value `"Anna"` instead of `{ "name": "Person.givenName", "value": "Anna" }`. Then I would expect the following map as return value:

```json
{
  "Lernstand-Mathe": "Bruchaddition",
  "Person.familyName": "Musterfrau",
  "Person.givenName": "Anna"
}
```

This is also the form which is the easiest to parse / handle for a consumer. 

> That's why we began to define requests which actually should be used also within templates in the future. Thus, a template would define several requests (e.g. for attributes, for privacy, ...) and the app would respond to these requests within the relationship requests.

**Comment by kulla** [comment]
> The app then summarizes the required and optional attributes into one map, with the keys being the queried attribute names and the values being the actual attribute within the user's data.

That's understandable. Lets take the example of `Person.givenName`. Isn't the user value `"Anna"` instead of `{ "name": "Person.givenName", "value": "Anna" }`. Then I would expect the following map as return value:

```json
{
  "Lernstand-Mathe": "Bruchaddition",
  "Person.familyName": "Musterfrau",
  "Person.givenName": "Anna"
}
```

This is also the form which is the easiest to parse / handle for a consumer (at least from our point of view). 

> That's why we began to define requests which actually should be used also within templates in the future. Thus, a template would define several requests (e.g. for attributes, for privacy, ...) and the app would respond to these requests within the relationship requests.

:+1: 

> We are currently working on the details. However, I would see also a map for the responses there (with the request id/key as the index). Would you rather have an array there?

A map is easier to parse then a list for the consumer. So the above object would IMHO be the best choice for the return value.

**Comment by stnmtz** [comment]
> This is also the form which is the easiest to parse / handle for a consumer (at least from our point of view).

Careful here: The attribute itself consists of name/value pairs, but the keys are the names you query within the template. Therefore, the key and the attribute's name might not be the same and there might be differences between the names you query and the names you receive within the objects. Yes, currently it is always the same as the App makes a direct string comparison. But there will be changes in the future which require that an attribute is an object rather than "just a string".

For example, attributes will receive some more metadata e.g. validFrom and validTo.

A request could look like the following in the near future:
```json
{
"Lernstand-Mathe": {
   "@type": "Attribute",
   "@version": 1
    "name": "Lernstand-Mathe",
    "value": "Bruchaddition",
    "validFrom":"2022-01-07T09:13:37Z"
  }
}
```

**Comment by kulla** [comment]
Okay, this makes sense! Especially since there will be more metadata in the future and the returned `name` might be different then the requested attribute. I close this issue then. Thanks for your explanation!
