### ISSUE TITLE
[FEATURE] Deployment Documentation for Connector

### ISSUE THREAD

**Issue by fdietz** [nmshd/feedback#3]
**Environment**
Connector

**Is your feature request related to a problem? Please describe.**
Documentation on how to deploy the connector. A step by step description how to deploy the connector on a popular cloud provider.

**Describe the solution you'd like**
For example, we use Heroku which doesn't support Docker volumnes (filesystem is ephemeral). We therefore can't use the `config.json`. Instead we require environment variables.

**Comment by jkoenig134** [comment]
Hello @fdietz, thank you for your feature request!

We are currently not supporting this, because the product was originally intended to run in the customer environment and not inside a cloud. We are planning to add configuration using env vars as a feature, but we can't give an ETA.

Please reach out via mail so that we can sort out a fast solution.

**Comment by kulla** [comment]
> We are planning to add configuration using env vars as a feature

It would be great when configuration can also be done via environment variables :smile: . For testing enmeshed locally we have added [code for setting up the connector locally](https://github.com/serlo/api.serlo.org/tree/e24e25b5240a46476c185dc049cdf83a37869f2d/enmeshed). Since we cannot publish `platformClientId` and `platformClientSecret` in our repository we have a file [config-dist.json](https://github.com/serlo/api.serlo.org/blob/e24e25b5240a46476c185dc049cdf83a37869f2d/enmeshed/config-dist.json) which needs to be copied to a local `config.json` and edited afterwards. Having environment variables `PLATFORM_CLIENT_ID` and `PLATFORM_CLIENT_SECRET` would help us since we can store them in an `.env` file which we do not store in git. So developers do not need to copy `config-dist.json` to their own `config.json` whenever we change the configuration.

**Comment by jkoenig134** [comment]
@kulla this was already sorted out.

We have a configuration only using env vars on our board.
I will keep this issue updated with news.

**Comment by jkoenig134** [comment]
Hey @kulla & @fdietz.
You can now install the [connector version 2.2.1](https://github.com/nmshd/cns-connector/pkgs/container/connector/15958454?tag=2.2.1) where this feature is implemented.
We also provided [some documentation for the configuration using environment variable](https://enmeshed.eu/integrate/connector-configuration#environment-variables).
